7 active storage
lina1812/qna pull request #6
Opened 2021-09-02 18:19 UTC by lina1812

2021-09-02 18:20 UTC, lina1812 commented
Реализовать следующие истории:
 - Пользователь может добавить один или несколько файлов при создании вопроса
 - Пользователь может добавить один или несколько файлов при создании ответа
 - Автор вопроса может добавить файлы при редактировании своего вопроса
 - Автор ответа может добавить файлы при редактировании своего ответа
 - Автор вопроса может удалить любой из прикрепленных к своему вопросу файлов
 - Автор ответа может удалить любой из прикрепленных к своему ответу файлов
 - Реализовать хранение файлов через Amazon S3 (или любое другое поддерживаемое облачное хранилище) и прямую загрузку с клиента (см. edgeguides.rubyonrails.org)

2021-09-03 09:43 UTC, vkurennov requested changes

2021-09-03 09:43 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def purge_file(file)
так у тебя будет дублирование и нарушение принципа единственной ответсвенности (почему контроллер **ответов** отвечает за **файлы**?). лушче сделать контроллер для файлов и в нем экшн destroy, родительскую модель у файла можно получить через метод `record`

2021-09-03 09:43 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def purge_file
а вот и дублирование

2021-09-03 11:48 UTC, vkurennov approved these changes

2021-09-03 11:54 UTC, merged